language: python

matrix:
    include:
    - python: 3.6
      env:
        - PYTHON_VERSION="3.6"
        - PYTEST_ARGS="-v "

install: source continuous_integration/install.sh

script: eval xvfb-run pytest $PYTEST_ARGS
# command to run tests
